.TH NNVIEW 1 "Release 6.6"
.\" (c) Copyright 1988, 1990, Kim F. Storm.  All rights reserved.
.UC 4
.SH NAME
nnview \- invokes nn on a folder
.SH SYNOPSIS
.B nnview
[ folder ]
.SH DESCRIPTION
.B nnview
will invoke nn on a folder, bypassing your .newsrc file entirely.
.LP
.SH SEE ALSO
nn(1)
.SH AUTHOR
Kim F. Storm, Texas Instruments A/S, Denmark
.br
E-mail: storm@texas.dk

